Сделал курсовую работу
Karenanna/SocksApp pull request #1
Opened 2023-02-26 11:45 UTC by Karenanna

Проверьте пожалуйста курсовую работу

2023-02-28 10:42 UTC, alekseykoshelev requested changes

2023-02-28 10:42 UTC, alekseykoshelev commented on src/main/java/pro/sky/socksapp/model/Socks.java
> +    public Socks(Color color, SocksSize socksSize, int cottonPercent, int quantity) {
Странный конструктор, нужно внутри присваивать поля.

2023-02-28 10:42 UTC, alekseykoshelev commented on src/main/java/pro/sky/socksapp/services/SocksFileServiceImpl.java
> +                long id = entry.getKey();
Тут нужно написать проверку, не факт, что первая сущность является нужной. Через условные операторы надо сравнивать параметры и уже у подходящего элемента увеличить количество

2023-03-01 08:10 UTC, Karenanna commented
Проверьте пожалуйста, сделал работу над ошибками

2023-03-04 07:24 UTC, merged